import type { Metadata } from "next";

import { Toaster } from 'sonner';

import ClientOnly from "@/src/components/layout/clientOny";
import Header from "@/src/components/layout/header";
import Footer from "@/src/components/layout/footer";
import Brand from "@/src/components/brand";

export const metadata: Metadata = {
  title: "Kokoria website version 1",
  description: "Generated by create Trong Luong",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientOnly/>
      <body>
        <Header/>
        <Toaster position="top-right" richColors closeButton/>

        <main className="container-fluid px-0">
          {children}
        </main>

        <Brand/>
        <Footer/>
        
      </body>
    </html>
  );
}
